// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.11.4
// source: proto_device.proto

package device

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceUploadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId     int64  `protobuf:"varint,1,opt,name=appId,proto3" json:"appId,omitempty"`
	Udi       string `protobuf:"bytes,2,opt,name=udi,proto3" json:"udi,omitempty"`
	AndroidId string `protobuf:"bytes,3,opt,name=androidId,proto3" json:"androidId,omitempty"`
	Imei      string `protobuf:"bytes,4,opt,name=imei,proto3" json:"imei,omitempty"`
	Mac       string `protobuf:"bytes,5,opt,name=mac,proto3" json:"mac,omitempty"`
	Idfa      string `protobuf:"bytes,6,opt,name=idfa,proto3" json:"idfa,omitempty"`
	Oaid      string `protobuf:"bytes,7,opt,name=oaid,proto3" json:"oaid,omitempty"`
}

func (x *DeviceUploadReq) Reset() {
	*x = DeviceUploadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_device_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceUploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceUploadReq) ProtoMessage() {}

func (x *DeviceUploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceUploadReq.ProtoReflect.Descriptor instead.
func (*DeviceUploadReq) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceUploadReq) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *DeviceUploadReq) GetUdi() string {
	if x != nil {
		return x.Udi
	}
	return ""
}

func (x *DeviceUploadReq) GetAndroidId() string {
	if x != nil {
		return x.AndroidId
	}
	return ""
}

func (x *DeviceUploadReq) GetImei() string {
	if x != nil {
		return x.Imei
	}
	return ""
}

func (x *DeviceUploadReq) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *DeviceUploadReq) GetIdfa() string {
	if x != nil {
		return x.Idfa
	}
	return ""
}

func (x *DeviceUploadReq) GetOaid() string {
	if x != nil {
		return x.Oaid
	}
	return ""
}

type DeviceUploadRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Udi string `protobuf:"bytes,1,opt,name=udi,proto3" json:"udi,omitempty"`
}

func (x *DeviceUploadRep) Reset() {
	*x = DeviceUploadRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_device_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceUploadRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceUploadRep) ProtoMessage() {}

func (x *DeviceUploadRep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceUploadRep.ProtoReflect.Descriptor instead.
func (*DeviceUploadRep) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceUploadRep) GetUdi() string {
	if x != nil {
		return x.Udi
	}
	return ""
}

type DeviceUdiGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId int64  `protobuf:"varint,1,opt,name=appId,proto3" json:"appId,omitempty"`
	Udi   string `protobuf:"bytes,2,opt,name=udi,proto3" json:"udi,omitempty"`
}

func (x *DeviceUdiGetReq) Reset() {
	*x = DeviceUdiGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_device_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceUdiGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceUdiGetReq) ProtoMessage() {}

func (x *DeviceUdiGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceUdiGetReq.ProtoReflect.Descriptor instead.
func (*DeviceUdiGetReq) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceUdiGetReq) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *DeviceUdiGetReq) GetUdi() string {
	if x != nil {
		return x.Udi
	}
	return ""
}

type DeviceIdGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId int64 `protobuf:"varint,1,opt,name=appId,proto3" json:"appId,omitempty"`
	Id    int64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeviceIdGetReq) Reset() {
	*x = DeviceIdGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_device_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceIdGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceIdGetReq) ProtoMessage() {}

func (x *DeviceIdGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceIdGetReq.ProtoReflect.Descriptor instead.
func (*DeviceIdGetReq) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceIdGetReq) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *DeviceIdGetReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeviceRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId     int64  `protobuf:"varint,1,opt,name=appId,proto3" json:"appId,omitempty"`
	Id        int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Udi       string `protobuf:"bytes,4,opt,name=udi,proto3" json:"udi,omitempty"`
	AndroidId string `protobuf:"bytes,5,opt,name=androidId,proto3" json:"androidId,omitempty"`
	Imei      string `protobuf:"bytes,6,opt,name=imei,proto3" json:"imei,omitempty"`
	Mac       string `protobuf:"bytes,7,opt,name=mac,proto3" json:"mac,omitempty"`
	Idfa      string `protobuf:"bytes,8,opt,name=idfa,proto3" json:"idfa,omitempty"`
	Oaid      string `protobuf:"bytes,9,opt,name=oaid,proto3" json:"oaid,omitempty"`
}

func (x *DeviceRep) Reset() {
	*x = DeviceRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_device_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceRep) ProtoMessage() {}

func (x *DeviceRep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceRep.ProtoReflect.Descriptor instead.
func (*DeviceRep) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceRep) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *DeviceRep) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeviceRep) GetUdi() string {
	if x != nil {
		return x.Udi
	}
	return ""
}

func (x *DeviceRep) GetAndroidId() string {
	if x != nil {
		return x.AndroidId
	}
	return ""
}

func (x *DeviceRep) GetImei() string {
	if x != nil {
		return x.Imei
	}
	return ""
}

func (x *DeviceRep) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *DeviceRep) GetIdfa() string {
	if x != nil {
		return x.Idfa
	}
	return ""
}

func (x *DeviceRep) GetOaid() string {
	if x != nil {
		return x.Oaid
	}
	return ""
}

type DevicePageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId int64 `protobuf:"varint,1,opt,name=appId,proto3" json:"appId,omitempty"`
	Page  int64 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size  int64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *DevicePageReq) Reset() {
	*x = DevicePageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_device_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DevicePageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevicePageReq) ProtoMessage() {}

func (x *DevicePageReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevicePageReq.ProtoReflect.Descriptor instead.
func (*DevicePageReq) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{5}
}

func (x *DevicePageReq) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *DevicePageReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *DevicePageReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type DevicePageData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Udi              string `protobuf:"bytes,4,opt,name=udi,proto3" json:"udi,omitempty"`
	AndroidId        string `protobuf:"bytes,5,opt,name=androidId,proto3" json:"androidId,omitempty"`
	Imei             string `protobuf:"bytes,6,opt,name=imei,proto3" json:"imei,omitempty"`
	Mac              string `protobuf:"bytes,7,opt,name=mac,proto3" json:"mac,omitempty"`
	Idfa             string `protobuf:"bytes,8,opt,name=idfa,proto3" json:"idfa,omitempty"`
	Oaid             string `protobuf:"bytes,9,opt,name=oaid,proto3" json:"oaid,omitempty"`
	ActiveStatus     int64  `protobuf:"varint,10,opt,name=activeStatus,proto3" json:"activeStatus,omitempty"`         //激活状态
	SecondStayStatus int64  `protobuf:"varint,11,opt,name=secondStayStatus,proto3" json:"secondStayStatus,omitempty"` //次留状态
}

func (x *DevicePageData) Reset() {
	*x = DevicePageData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_device_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DevicePageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevicePageData) ProtoMessage() {}

func (x *DevicePageData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevicePageData.ProtoReflect.Descriptor instead.
func (*DevicePageData) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{6}
}

func (x *DevicePageData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DevicePageData) GetUdi() string {
	if x != nil {
		return x.Udi
	}
	return ""
}

func (x *DevicePageData) GetAndroidId() string {
	if x != nil {
		return x.AndroidId
	}
	return ""
}

func (x *DevicePageData) GetImei() string {
	if x != nil {
		return x.Imei
	}
	return ""
}

func (x *DevicePageData) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *DevicePageData) GetIdfa() string {
	if x != nil {
		return x.Idfa
	}
	return ""
}

func (x *DevicePageData) GetOaid() string {
	if x != nil {
		return x.Oaid
	}
	return ""
}

func (x *DevicePageData) GetActiveStatus() int64 {
	if x != nil {
		return x.ActiveStatus
	}
	return 0
}

func (x *DevicePageData) GetSecondStayStatus() int64 {
	if x != nil {
		return x.SecondStayStatus
	}
	return 0
}

type DevicePageRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64             `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data  []*DevicePageData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *DevicePageRep) Reset() {
	*x = DevicePageRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_device_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DevicePageRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevicePageRep) ProtoMessage() {}

func (x *DevicePageRep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevicePageRep.ProtoReflect.Descriptor instead.
func (*DevicePageRep) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{7}
}

func (x *DevicePageRep) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DevicePageRep) GetData() []*DevicePageData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_device_proto protoreflect.FileDescriptor

var file_proto_device_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x22, 0xa5, 0x01, 0x0a,
	0x0f, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71,
	0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x64, 0x69, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x64, 0x69, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x6e, 0x64, 0x72,
	0x6f, 0x69, 0x64, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x6e, 0x64,
	0x72, 0x6f, 0x69, 0x64, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6d, 0x65, 0x69, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6d, 0x65, 0x69, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61,
	0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x61, 0x63, 0x12, 0x12, 0x0a, 0x04,
	0x69, 0x64, 0x66, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x64, 0x66, 0x61,
	0x12, 0x12, 0x0a, 0x04, 0x6f, 0x61, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6f, 0x61, 0x69, 0x64, 0x22, 0x23, 0x0a, 0x0f, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x64, 0x69, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x64, 0x69, 0x22, 0x39, 0x0a, 0x0f, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x55, 0x64, 0x69, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05,
	0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x61, 0x70, 0x70,
	0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x64, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x64, 0x69, 0x22, 0x36, 0x0a, 0x0e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0xaf, 0x01, 0x0a,
	0x09, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70,
	0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x64, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x64, 0x69, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x49, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x69, 0x6d, 0x65, 0x69, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x69, 0x6d, 0x65, 0x69, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x61, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x64, 0x66, 0x61, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x64, 0x66, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x61,
	0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6f, 0x61, 0x69, 0x64, 0x22, 0x4d,
	0x0a, 0x0d, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0xee, 0x01,
	0x0a, 0x0e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x64, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x64, 0x69, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x49, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x69, 0x6d, 0x65, 0x69, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x69, 0x6d, 0x65, 0x69, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x61, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x64, 0x66, 0x61, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x64, 0x66, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x61,
	0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6f, 0x61, 0x69, 0x64, 0x12, 0x22,
	0x0a, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x2a, 0x0a, 0x10, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x79,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x73, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x51,
	0x0a, 0x0d, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x50, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x32, 0x8f, 0x02, 0x0a, 0x0d, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x0c, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x12, 0x17, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x70, 0x1a, 0x17, 0x2e, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x70, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0e, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x47, 0x65, 0x74, 0x42, 0x79, 0x55, 0x64, 0x69, 0x12, 0x17, 0x2e, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x55, 0x64, 0x69, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x11, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x70, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x09, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x47, 0x65, 0x74, 0x12, 0x16, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x22,
	0x00, 0x12, 0x40, 0x0a, 0x0e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x61, 0x67, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x15, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x70, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_device_proto_rawDescOnce sync.Once
	file_proto_device_proto_rawDescData = file_proto_device_proto_rawDesc
)

func file_proto_device_proto_rawDescGZIP() []byte {
	file_proto_device_proto_rawDescOnce.Do(func() {
		file_proto_device_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_device_proto_rawDescData)
	})
	return file_proto_device_proto_rawDescData
}

var file_proto_device_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_device_proto_goTypes = []interface{}{
	(*DeviceUploadReq)(nil), // 0: device.DeviceUploadReq
	(*DeviceUploadRep)(nil), // 1: device.DeviceUploadRep
	(*DeviceUdiGetReq)(nil), // 2: device.DeviceUdiGetReq
	(*DeviceIdGetReq)(nil),  // 3: device.DeviceIdGetReq
	(*DeviceRep)(nil),       // 4: device.DeviceRep
	(*DevicePageReq)(nil),   // 5: device.DevicePageReq
	(*DevicePageData)(nil),  // 6: device.DevicePageData
	(*DevicePageRep)(nil),   // 7: device.DevicePageRep
}
var file_proto_device_proto_depIdxs = []int32{
	6, // 0: device.DevicePageRep.data:type_name -> device.DevicePageData
	1, // 1: device.DeviceService.DeviceUpload:input_type -> device.DeviceUploadRep
	2, // 2: device.DeviceService.DeviceGetByUdi:input_type -> device.DeviceUdiGetReq
	3, // 3: device.DeviceService.DeviceGet:input_type -> device.DeviceIdGetReq
	5, // 4: device.DeviceService.DevicePageList:input_type -> device.DevicePageReq
	1, // 5: device.DeviceService.DeviceUpload:output_type -> device.DeviceUploadRep
	4, // 6: device.DeviceService.DeviceGetByUdi:output_type -> device.DeviceRep
	4, // 7: device.DeviceService.DeviceGet:output_type -> device.DeviceRep
	7, // 8: device.DeviceService.DevicePageList:output_type -> device.DevicePageRep
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_device_proto_init() }
func file_proto_device_proto_init() {
	if File_proto_device_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_device_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceUploadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_device_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceUploadRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_device_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceUdiGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_device_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceIdGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_device_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_device_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DevicePageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_device_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DevicePageData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_device_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DevicePageRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_device_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_device_proto_goTypes,
		DependencyIndexes: file_proto_device_proto_depIdxs,
		MessageInfos:      file_proto_device_proto_msgTypes,
	}.Build()
	File_proto_device_proto = out.File
	file_proto_device_proto_rawDesc = nil
	file_proto_device_proto_goTypes = nil
	file_proto_device_proto_depIdxs = nil
}
