// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.11.4
// source: proto_push.proto

package push

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushVendorSaveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId                 int64  `protobuf:"varint,1,opt,name=appId,proto3" json:"appId,omitempty"`
	Vendor                string `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	VendorAppId           string `protobuf:"bytes,3,opt,name=vendorAppId,proto3" json:"vendorAppId,omitempty"`
	VendorAppKey          string `protobuf:"bytes,4,opt,name=vendorAppKey,proto3" json:"vendorAppKey,omitempty"`
	VendorAppSecret       string `protobuf:"bytes,5,opt,name=vendorAppSecret,proto3" json:"vendorAppSecret,omitempty"`
	VendorAppMasterSecret string `protobuf:"bytes,6,opt,name=vendorAppMasterSecret,proto3" json:"vendorAppMasterSecret,omitempty"`
}

func (x *PushVendorSaveReq) Reset() {
	*x = PushVendorSaveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_push_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushVendorSaveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushVendorSaveReq) ProtoMessage() {}

func (x *PushVendorSaveReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_push_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushVendorSaveReq.ProtoReflect.Descriptor instead.
func (*PushVendorSaveReq) Descriptor() ([]byte, []int) {
	return file_proto_push_proto_rawDescGZIP(), []int{0}
}

func (x *PushVendorSaveReq) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *PushVendorSaveReq) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *PushVendorSaveReq) GetVendorAppId() string {
	if x != nil {
		return x.VendorAppId
	}
	return ""
}

func (x *PushVendorSaveReq) GetVendorAppKey() string {
	if x != nil {
		return x.VendorAppKey
	}
	return ""
}

func (x *PushVendorSaveReq) GetVendorAppSecret() string {
	if x != nil {
		return x.VendorAppSecret
	}
	return ""
}

func (x *PushVendorSaveReq) GetVendorAppMasterSecret() string {
	if x != nil {
		return x.VendorAppMasterSecret
	}
	return ""
}

type PushVendorSaveRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PushVendorSaveRep) Reset() {
	*x = PushVendorSaveRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_push_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushVendorSaveRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushVendorSaveRep) ProtoMessage() {}

func (x *PushVendorSaveRep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_push_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushVendorSaveRep.ProtoReflect.Descriptor instead.
func (*PushVendorSaveRep) Descriptor() ([]byte, []int) {
	return file_proto_push_proto_rawDescGZIP(), []int{1}
}

func (x *PushVendorSaveRep) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CidUploadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId int64  `protobuf:"varint,1,opt,name=appId,proto3" json:"appId,omitempty"`
	Udi   string `protobuf:"bytes,2,opt,name=udi,proto3" json:"udi,omitempty"`
	Cid   string `protobuf:"bytes,3,opt,name=cid,proto3" json:"cid,omitempty"`
}

func (x *CidUploadReq) Reset() {
	*x = CidUploadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_push_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CidUploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CidUploadReq) ProtoMessage() {}

func (x *CidUploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_push_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CidUploadReq.ProtoReflect.Descriptor instead.
func (*CidUploadReq) Descriptor() ([]byte, []int) {
	return file_proto_push_proto_rawDescGZIP(), []int{2}
}

func (x *CidUploadReq) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *CidUploadReq) GetUdi() string {
	if x != nil {
		return x.Udi
	}
	return ""
}

func (x *CidUploadReq) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

type CidUploadRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CidUploadRep) Reset() {
	*x = CidUploadRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_push_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CidUploadRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CidUploadRep) ProtoMessage() {}

func (x *CidUploadRep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_push_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CidUploadRep.ProtoReflect.Descriptor instead.
func (*CidUploadRep) Descriptor() ([]byte, []int) {
	return file_proto_push_proto_rawDescGZIP(), []int{3}
}

type PushToUdiReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId int64    `protobuf:"varint,1,opt,name=appId,proto3" json:"appId,omitempty"`
	Udi   []string `protobuf:"bytes,2,rep,name=udi,proto3" json:"udi,omitempty"`
}

func (x *PushToUdiReq) Reset() {
	*x = PushToUdiReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_push_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushToUdiReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushToUdiReq) ProtoMessage() {}

func (x *PushToUdiReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_push_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushToUdiReq.ProtoReflect.Descriptor instead.
func (*PushToUdiReq) Descriptor() ([]byte, []int) {
	return file_proto_push_proto_rawDescGZIP(), []int{4}
}

func (x *PushToUdiReq) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *PushToUdiReq) GetUdi() []string {
	if x != nil {
		return x.Udi
	}
	return nil
}

type PushToUdiRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PushToUdiRep) Reset() {
	*x = PushToUdiRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_push_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushToUdiRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushToUdiRep) ProtoMessage() {}

func (x *PushToUdiRep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_push_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushToUdiRep.ProtoReflect.Descriptor instead.
func (*PushToUdiRep) Descriptor() ([]byte, []int) {
	return file_proto_push_proto_rawDescGZIP(), []int{5}
}

type TranToUdiReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId int64    `protobuf:"varint,1,opt,name=appId,proto3" json:"appId,omitempty"`
	Udi   []string `protobuf:"bytes,2,rep,name=udi,proto3" json:"udi,omitempty"`
}

func (x *TranToUdiReq) Reset() {
	*x = TranToUdiReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_push_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranToUdiReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranToUdiReq) ProtoMessage() {}

func (x *TranToUdiReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_push_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranToUdiReq.ProtoReflect.Descriptor instead.
func (*TranToUdiReq) Descriptor() ([]byte, []int) {
	return file_proto_push_proto_rawDescGZIP(), []int{6}
}

func (x *TranToUdiReq) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *TranToUdiReq) GetUdi() []string {
	if x != nil {
		return x.Udi
	}
	return nil
}

type TranToUdiRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TranToUdiRep) Reset() {
	*x = TranToUdiRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_push_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranToUdiRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranToUdiRep) ProtoMessage() {}

func (x *TranToUdiRep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_push_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranToUdiRep.ProtoReflect.Descriptor instead.
func (*TranToUdiRep) Descriptor() ([]byte, []int) {
	return file_proto_push_proto_rawDescGZIP(), []int{7}
}

var File_proto_push_proto protoreflect.FileDescriptor

var file_proto_push_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x70, 0x75, 0x73, 0x68, 0x22, 0xe7, 0x01, 0x0a, 0x11, 0x50, 0x75, 0x73,
	0x68, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x12, 0x14,
	0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x61,
	0x70, 0x70, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x12, 0x20, 0x0a, 0x0b,
	0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x41, 0x70, 0x70, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x41, 0x70, 0x70, 0x49, 0x64, 0x12, 0x22,
	0x0a, 0x0c, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x41, 0x70, 0x70, 0x4b, 0x65, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x41, 0x70, 0x70, 0x4b,
	0x65, 0x79, 0x12, 0x28, 0x0a, 0x0f, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x41, 0x70, 0x70, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x76, 0x65, 0x6e,
	0x64, 0x6f, 0x72, 0x41, 0x70, 0x70, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x34, 0x0a, 0x15,
	0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x41, 0x70, 0x70, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x76, 0x65, 0x6e,
	0x64, 0x6f, 0x72, 0x41, 0x70, 0x70, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x22, 0x23, 0x0a, 0x11, 0x50, 0x75, 0x73, 0x68, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72,
	0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x48, 0x0a, 0x0c, 0x43, 0x69, 0x64, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x64, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x64, 0x69, 0x12,
	0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69,
	0x64, 0x22, 0x0e, 0x0a, 0x0c, 0x43, 0x69, 0x64, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65,
	0x70, 0x22, 0x36, 0x0a, 0x0c, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x55, 0x64, 0x69, 0x52, 0x65,
	0x71, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x64, 0x69, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x75, 0x64, 0x69, 0x22, 0x0e, 0x0a, 0x0c, 0x50, 0x75, 0x73,
	0x68, 0x54, 0x6f, 0x55, 0x64, 0x69, 0x52, 0x65, 0x70, 0x22, 0x36, 0x0a, 0x0c, 0x54, 0x72, 0x61,
	0x6e, 0x54, 0x6f, 0x55, 0x64, 0x69, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x64, 0x69, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x75, 0x64,
	0x69, 0x22, 0x0e, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x6e, 0x54, 0x6f, 0x55, 0x64, 0x69, 0x52, 0x65,
	0x70, 0x32, 0xf8, 0x01, 0x0a, 0x0b, 0x50, 0x75, 0x73, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x44, 0x0a, 0x0e, 0x50, 0x75, 0x73, 0x68, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x53,
	0x61, 0x76, 0x65, 0x12, 0x17, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x56,
	0x65, 0x6e, 0x64, 0x6f, 0x72, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70,
	0x75, 0x73, 0x68, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x53, 0x61,
	0x76, 0x65, 0x52, 0x65, 0x70, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x09, 0x43, 0x69, 0x64, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x12, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x43, 0x69, 0x64, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e,
	0x43, 0x69, 0x64, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x70, 0x22, 0x00, 0x12, 0x35,
	0x0a, 0x09, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x55, 0x64, 0x69, 0x12, 0x12, 0x2e, 0x70, 0x75,
	0x73, 0x68, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x55, 0x64, 0x69, 0x52, 0x65, 0x71, 0x1a,
	0x12, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x55, 0x64, 0x69,
	0x52, 0x65, 0x70, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x6e, 0x54, 0x6f, 0x55,
	0x64, 0x69, 0x12, 0x12, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x54, 0x6f,
	0x55, 0x64, 0x69, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x54, 0x72,
	0x61, 0x6e, 0x54, 0x6f, 0x55, 0x64, 0x69, 0x52, 0x65, 0x70, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05,
	0x2f, 0x70, 0x75, 0x73, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_push_proto_rawDescOnce sync.Once
	file_proto_push_proto_rawDescData = file_proto_push_proto_rawDesc
)

func file_proto_push_proto_rawDescGZIP() []byte {
	file_proto_push_proto_rawDescOnce.Do(func() {
		file_proto_push_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_push_proto_rawDescData)
	})
	return file_proto_push_proto_rawDescData
}

var file_proto_push_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_push_proto_goTypes = []interface{}{
	(*PushVendorSaveReq)(nil), // 0: push.PushVendorSaveReq
	(*PushVendorSaveRep)(nil), // 1: push.PushVendorSaveRep
	(*CidUploadReq)(nil),      // 2: push.CidUploadReq
	(*CidUploadRep)(nil),      // 3: push.CidUploadRep
	(*PushToUdiReq)(nil),      // 4: push.PushToUdiReq
	(*PushToUdiRep)(nil),      // 5: push.PushToUdiRep
	(*TranToUdiReq)(nil),      // 6: push.TranToUdiReq
	(*TranToUdiRep)(nil),      // 7: push.TranToUdiRep
}
var file_proto_push_proto_depIdxs = []int32{
	0, // 0: push.PushService.PushVendorSave:input_type -> push.PushVendorSaveReq
	2, // 1: push.PushService.CidUpload:input_type -> push.CidUploadReq
	4, // 2: push.PushService.PushToUdi:input_type -> push.PushToUdiReq
	6, // 3: push.PushService.TranToUdi:input_type -> push.TranToUdiReq
	1, // 4: push.PushService.PushVendorSave:output_type -> push.PushVendorSaveRep
	3, // 5: push.PushService.CidUpload:output_type -> push.CidUploadRep
	5, // 6: push.PushService.PushToUdi:output_type -> push.PushToUdiRep
	7, // 7: push.PushService.TranToUdi:output_type -> push.TranToUdiRep
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_push_proto_init() }
func file_proto_push_proto_init() {
	if File_proto_push_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_push_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushVendorSaveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_push_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushVendorSaveRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_push_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CidUploadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_push_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CidUploadRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_push_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushToUdiReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_push_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushToUdiRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_push_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranToUdiReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_push_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranToUdiRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_push_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_push_proto_goTypes,
		DependencyIndexes: file_proto_push_proto_depIdxs,
		MessageInfos:      file_proto_push_proto_msgTypes,
	}.Build()
	File_proto_push_proto = out.File
	file_proto_push_proto_rawDesc = nil
	file_proto_push_proto_goTypes = nil
	file_proto_push_proto_depIdxs = nil
}
